name: deployment
on:
  push:
    branches:
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Sets the environment to the branch that it's on.
    environment: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'staging' }}

    # When adding a service, add the variables/secrets here
    env:
      test: test

    steps:
      - uses: actions/checkout@v4
      - name: Check for Dockerfile(s)
        run: |
          if [ -f Dockerfile ]; then
          echo "Dockerfile exists in this directory."
          else
            echo "Dockerfile does not exist in this directory."
          fi

      - name: Build Project
        run: docker build .

      - name: Deploy to Environment
        run: echo "Insert deployment commands or scripts here"
