name: pre-deployment validation
on:
  pull_request:
    branches:
      - staging

jobs:
  buildableAsDockerImage:
    runs-on: ubuntu-latest

    # Sets the environment to the branch that it's on.
    environment: staging
    # When adding a service, add the variables/secrets here
    env:
      test: test

    steps:
      - uses: actions/checkout@v4
      - name: Check for Dockerfile(s)
        run: |
          if [ -f Dockerfile ]; then
            echo "Dockerfile exists in this directory."
          else
            echo "Dockerfile does not exist in this directory."
          fi
      - name: Build Docker Image
        run: |
          docker build -t myapp:${{ github.sha }} .
